package com.example.quizapplication;

public class Questions {

    public static int categoryCount = 0;
    public static int questCounter = 0;
    public static int questionC = 0;

    public String mQuestions[] = {
            "If you are <b><u>ambivalent</u></b> with the answers, analyze the given problem.",
            "He left the country because of the <b><u>ominous</u></b> experiences he had in the past.",
            "Teenagers are easily <b><u>susceptible</u></b> to peer influence.",
            "My mother is always <b><u>adamant</u></b> in eating breakfast before leaving the house.",
            "Reading words without understanding their meaning is <b><u>futile</u></b>.",
            "She wears gold but people knows how <b><u>ostentatious</u></b> she can be.",
            "He submitted a  <b><u>grotesque</u></b> artwork that nobody in the class could relate to.",
            "Their <b><u>clandestine</u></b> affair remained unknown for three years.",
            "They say love is like a firework, a <b><u>fleeting</u></b> moment.",
            "Cara is repulsive and rebellious. She always speaks <b><u>sordid</u></b> words.",
            "Every time I see Cathy looking at me, I feel <b><u>Euphoria</u></b> in my bones.",
            "I bought this book because when I read the <b><u>blurb</u></b> at the back, I fell in love with it.",
            "Finding a way out of the <b><u>labyrinth</u></b> is the last challenge of the competition.",
            "There is still love in our hearts amidst our seemingly <b><u>mundane</u></b> existence.",
            "Cassy has a strong <b><u>penchant</u></b> in collecting cars.",

            "Diskettes and CDs are going <b><u>obsolete</u></b>.",
            "The Queen of the Night dances <b><u>vivaciously</u></b>.",
            "The court released a <b><u>dogmatic</u></b> statement that made people more hopeful.",
            "This generation is prone to <b><u>plethoric</u></b> use of mobile gadgets.",
            "I am usually <b><u>haphazard</u></b> in composing my poetry but they turn out so well anyway.",
            "Tommy was a real <b><u>avid</u></b> baseball card collector. He inherited the desire to collect cards because his dad had a collection, too",
            "Her Christmas bills added up. After the holidays, her <b><u>extravagance</u></b> was going to take several months to pay off.",
            "It was <b><u>gratifying</u></b> to see how she acted toward her grandmother because her grandmother was always kind to her.",
            "The boys was caught stealing from the store. His <b><u>larceny</u></b> caught up with him when the owner showed him a video tape.",
            "The ideas she presented to the class were clearly an untested <b><u>theory</u></b> because there had never been any research done on it.",
            "His <b><u>eternal</u></b> light would shine on the people even after his death.",
            "He cut the paper <b><u>precisely</u></b> on the line, and it fit perfectly in the grooves of the picture frame.",
            "The boy tried to <b><u>justify</u></b> his actions to his mother by explaining the reasons why he did what he did.",
            "She did several backbends in a row to show how <b><u><limber</u></b> she was, so that she could be chosen for the squad.",
            "<small>He climbed the mountain and stood looking over the tops of the trees on the mountain across from him. He was right on the <b><u>precipice</u></b> and could have fallen.</small>",
            //30
            "I regard him as a man of integrity and high professional <b><u>competence</u></b>.",
            "There is no need to show <b><u>compassion</u></b> for him.",
            " called the police when my neighbors refused to settle down and end their <b><u>revelry</u></b>.",
            "It was a <b><u>ruse</u></b> to bring him there.",
            "The movie was very <b><u>vivid</u></b>.",
            "He is a <b><u>simpleton</u></b> boy and tries to make everybody around him laugh.",
            "The child should be kept away from <b><u>libidinous</u></b> movie.",
            "Celebrities believe in wearing <b><u>clannish</u></b> dresses",
            "The valley was <b><u>speckle</u></b> with flowers.",
            "The Kids <b><u>befoul</u></b> their hands by playing in the garden. ",
            "His father’s <b><u>satanic</u></b> remark stung deeply and brought the boy to tears.",
            "He always refused any <b><u>titular</u></b> distinction; but he was credited by many.",
            "During weekends the street markets are in a state of <b><u>flurry</u></b>.",
            "I found myself in a <b><u>quandary</u></b>.",
            "Ayesha lived here in <b><u>quietude</u></b>.",

            "The new book concludes in a way that hardly matches my own social <b><u>proclivity</u></b>.",
            "He was proved to be a <b><u>quisling</u></b>.",
            "He is a <b><u>plebian</u></b> author.",
            "Her <b><u>opulence</u></b> made her have many friends.",
            "Climatic conditions <b><u></u></b>obviate the necessity of rain.",
            "The new guest smiled in return but gave no <b><u>overt</u></b> sign of knowing the man.",
            "She made a <b><u>meddlesome</u></b> remark",
            "Naira can’t put up with his <b><u>mincing</u></b> voice for rest of her life.",
            "She came to a grief because of his <b><u>lavish</u></b> spending habits.",
            "Though his speech was <b><u>laconic</u></b>, yet it was lucid.",
            "A <b><u>mammoth</u></b> project will be completed very soon.",
            "Terrorism is a potential <b><u>menace</u></b> to the integrity of the country.",
            "His evil intentions were <b><u>manifest</u></b> when he mentioned the question of dowry.",
            "There is no <b><u>modicum</u></b> of truth in her statement.",
            "He drank himself into <b><u>oblivion</u></b>.",
            //60
            "A person can <b><u>refurbish</u></b> his image by leading life dedicated to his vocation.",
            "Dozens Of villages have been <b><u>razed</u></b>.",
            "He listened to the speaker with <b><u>rapt</u></b> attention.",
            "In order to <b><u>perpetuate</u></b> the method of amending the constitution was made extremely rigid.",
            "He died of a <b><u>malignant</u></b> tumor.",
            "We should not try to <b><u>denigrate</u></b> the character of anyone.",
            "Zulfiqar Ali Bhutto as a <b><u>dauntless</u></b> politician.",
            "We all should maintain our <b><u>decorum</u></b>.",
            "Smoking is a <b><u>detriment</u></b> to good health.",
            "I will have to go another <b><u>dreary</u></b> meeting tomorrow.",
            "His <b><u>grotesque</u></b> appearance makes him defame.",
            "He players <b><u>glided</u></b> across the field easily.",
            "Ahmed <b><u>Gingerly</u></b> moved his injured foot.",
            "The sages <b><u>teem</u></b> with references to the inhabitants.",
            "Urooj is a <b><u>chunky</u></b> fellow of mine.",

            "Rehana went to the window and <b><u>hasped</u></b> it.",
            "Nisha was talking in <b><u>undertone</u></b>.",
            "The passengers escaped <b><u>unscathed</u></b>.",
            "The painter <b><u>varnished</u></b> the doors.",
            "They <b><u>touted</u></b> her performance.",
            "The applause from the audience was <b><u>tepid</u></b>.",
            "Some people are said to have revealed no <b><u>vestige</u></b> of religion.",
            "The notion of scarcity is <b><u>ingrained</u></b> in them.",
            "The <b><u>feud</u></b> between the two sisters lasted for two hours.",
            "There was no longer any <b><u>fluster</u></b> or hesitation in his manner.",
            "Everyone expect <b><u>fealty</u></b> from their good friends.",
            "The subject was <b><u>broached</u></b> to nurture the students in a better way.",
            "Sania gave him a <b><u>coy</u></b> smile",
            "He <b><u>concocted</u></b> an idea to start a new business.",
            "He had been <b><u>dilatory</u></b> but now he intended to get down to business.",
           //90
            "The liquid easily pervades through a loosely-knitted material, but through a thick material, it clots._________________",
            "Those tall turbines will not mar the landscape, instead they will make the surface of the earth beautiful._______________",
            "<small>A man who is adroit has several was of solving problems; an inexperienced man on the other hand can think of the only one way to solve his problem._________________</small>",
            " He is not a yes-man, but a strong Critic of the group._________________",
            "Those are not environmental backlash, but inspirational words to the earth- savers group. _________________",
            "<small>A smattering of the knowledge about a Job will result in a a slow promotion, but an in-depth knowledge will lead to a better paying capacity.__________________</small>",
            "Sarah gives an ingratiating smile instead of a sincere one jn front of the helpless people.__________________",
            "Roel is a whiz figures, but dull in language learning.__________________",
            "Tanya's further explanation won't make the agreement closure; on the contrary, they'll make the terms of the contract clearer.___________________",
            "He would rather jiggle to show that he listening to the teacher than to remain like's s statue._________________",
            "It was a <b><u>ruse</u></b> to bring him there _______________",
            "The beach is <b><u>rife</u></b> with young people during the summer months._____________",
            "Sania gave him a <b><u>coy</u></b> smile.____________",
            "Everyone expect <b><u>fealty</u></b> from their good friends._____________",
            "The kids <b><u><gamboled/u></b> all around the house.",

            "The <b><u>ignominious</u></b> stealing has given him nefarious identity.",
            "Our management will not <b><u>countenance</u></b> cheating.",
            "A deel gave a harsh, <b><u>derisive</u></b> laugh.",
            "Many lights are shimmering in the <b><u>gloaming</u></b>.",
            "A great leader renders <b><u>disinterested</u></b> services to his society.",
            "Ejaz <b><u>pilfered</u></b> enough pieces of wood from the factory to make a chair.",
            "It only remained to <b><u>caulk</u></b> their important task, and this occupied them for a day or two.",
            "The teacher’s <b><u>plea</u></b> foe silence went unheard, resulting in extreme discomfort to the student.",
            "Shehrish is a <b><u>jovial</u></b> fellow.",
            "Ali is a very <b><u>hilarious</u></b> student in the class.",
            "Take a Disprin to <b><u>alleviate</u></b> your headache.",
            "She had a low <b><u>tolerance</u></b> for noise.",
            "The <b><u>conceited</u></b> man would not stop talking about himself.",
            "To win elections, politicians often make <b><u>spurious</u></b> promises to voters.",
            "He treated all his colleagues with the same level of <b><u>esteem</u></b>.",
            //120
            "It may have been a simple <b><u>ridicule</u></b>, but it still made him feel rejected.",
            "This  <b><u>persiflage</u></b> is not appropriate when we have such serious problems to discuss.",
            "She tried to <b><u>endear</u></b> everyone.",
            "The sorcerer knows an <b><u>incantation </u></b>to raise the dead.",
            "Don’t <b><u>dally</u></b> otherwise we’ll miss the train.",
            "The report confirmed their <b><u>exemption</u></b> from military duty.",
            "My brother Imran is <b><u>fickle</u></b> by nature.",
            "Don’t believe her story because it is just <b><u>Fictitious</u></b>.",
            "I am very <b><u>irate</u></b> person therefore my wife dislikes me.",
            "His <b><u>facile</u></b> win tells us he’s in form",
            "Shazia is very <b><u>irresolute</u></b> by nature.",
            "She left home in <b><u>pursuit</u></b> of happiness.",
            "She would face that fear – <b><u>ferret</u></b>it out and destroy it.",
            "The dog will <b><u>rummage</u></b> through the garbage for food when it gets hungry.",
            "The weather was too <b><u>wintry </u></b>for me to go outside.",

            "The professor will take his family on a long vacation during his <b><u>hiatus.va</u></b>",
            "His look was one of <b><u>frigid</u></b> anger as he stormed out.",
            "Most ferrous materials are <b><u>magnetic</u></b>.",
            "This is <b><u>remissible</u></b> to apply for CSS exam.",
            "After his examination result he was in <b><u>melancholia</u></b>.",
            "As soon as they shake hands <b><u>docility </u></b>reflects from their gesture.",
            "Everybody admires Aleena because she is a <b><u>quintessence</u></b> of benevolence.",
            "The mentally ill patients are the last to feel <b><u>qualms</u></b> while committing cruel deeds",
            "Emission from diesel cars producing <b><u>noxious</u></b> gases causes air pollution.",
            "<b><u>Narcissism</u></b> leads to selfishness in character.",
            "A <b><u>mammoth</u></b> project will be completed very soon.",
            "Terrorism is a potential <b><u>menace</u></b> to the integrity of the country.",
            "His evil intentions were <b><u>manifest</u></b> when he mentioned the question of dowry.",
            "There is no <b><u>modicum </u></b> of truth in her statement.",
            "He drank himself into <b><u>oblivion</u></b>.",
            //150
            "A person can <b><u>refurbish</u></b> his image by leading life dedicated to his vocation.",
            "Dozens Of villages have been <b><u>razed</u></b>.",
            "He listened to the speaker with <b><u>rapt</u></b> attention.",
            "In order to <b><u>perpetuate</u></b> the method of amending the constitution was made extremely rigid.",
            "He died of a <b><u>malignant</u></b> tumor.",
            "We should not try to <b><u>denigrate</u></b> the character of anyone.",
            "Zulfiqar Ali Bhutto as a <b><u>dauntless</u></b> politician.",
            "We all should maintain our <b><u>decorum</u></b>.",
            "Smoking is a <b><u>detriment</u></b> to good health.",
            "I will have to go another <b><u>dreary</u></b> meeting tomorrow",
            "His <b><u>grotesque</u></b> appearance makes him defame.",
            "He players <b><u>glided</u></b> across the field easily.",
            "Ahmed <b><u>Gingerly</u></b> moved his injured foot.",
            "The sages <b><u>teem</u></b> with references to the inhabitants",
            "Urooj is a <b><u>chunky</u></b> fellow of mine.",
            //    <b><u></u></b>
            "Rehana went to the window and <b><u>hasped</u></b> it.",
            "Nisha was talking in <b><u>undertone</u></b>.",
            "The passengers escaped <b><u>unscathed</u></b>.",
            "The painter <b><u>varnished</u></b> the doors.",
            "They <b><u>touted</u></b> her performance.",
            "The applause from the audience was <b><u>tepid</u></b>.",
            "Some people are said to have revealed no <b><u>vestige</u></b> of religion.",
            "The notion of scarcity is <b><u>ingrained</u></b> in them.",
            "The <b><u>feud</u></b> between the two sisters lasted for two hours",
            "There was no longer any <b><u>fluster</u></b> or hesitation in his manner.",
            "Everyone expect <b><u>fealty</u></b> from their good friends.",
            "The subject was <b><u>broached</u></b> to nurture the students in a better way.",
            "Sania gave him a <b><u>coy</u></b> smile.",
            "He <b><u>concocted</u></b> an idea to start a new business.",
            "He had been <b><u>dilatory</u></b> but now he intended to get down to business.",
            //180
            "Which sentence uses “famish” correctly?",
            "Priscila _______ rather not invest her savings in the stock market.",
            "Did you have any problem ______ our house?",
            "I hope you don’t mind _____ joining you.",
            "Most basketball players are 6 ____ tall or more.",
            "These children _____ how to improvise more props for the play.",
            "The company will upgrade ______ computer systems next week.",
            "Clara ___________ three thousand words for her essay.",
            "You have too many _______ but few time to prove you’re right.",
            "Neither Sarah nor Tina _______ the crime yesterday.",
            "You do like going to the party alone. _____you?",
            "We had our house _______ in yellow.",
            "He has been exercising but his immune system was steadily _________.",
            "I was ______ that the weather would be sunny and we would be able to enjoy our swimming.",
            "I think it’s not a great idea. I totally ______.",

            "So many ___________ I found in the library, now I’m ready to report.",
            "My grandpa always feed his flock of _______ early in the morning.",
            "Happy memories are always remembered, not ________.",
            "Flight Z735 ______ yesterday. 350 passengers died in that accident.",
            "There is a ________ message when you look closely at her painting.",
            "Let's go, ______",
            "Andrew isn't sleeping, ______",
            "Sue wasn't listening, _______",
            "Are there _______apples in the kitchen?",
            "Despite ________ hard, he failed the exam",
            "I'll _______their cat while they are away on holiday.",
            "Their car does 150 miles ________hour.",
            "See you on ________Wednesday.",
            "I ________had this computer for three years.",
            "The match ______ already started when we arrived.",
            //210
            "Blessed _____ the poor for they shall inherit the kingdom of God.",
            " We had our house________ in yellow.",
            "I prefer tea _____ coffee.",

            "FOR__ __ DDEN",
            "T___LASSEMIA",
            "A__ __ ITIES",
            "SACCHA__ __",
            "JAGG__ __ST",
            "APA____",
            "YACH__ __MAN",
            "PER___TRATOR",
            "TOR_____TING",
            "SCABB__",
            "DU___IER",
            "ILE___S",
            "UBI___TOUS",
            "___CEOUS",
            "____YARD",

            "M____MONICS",
            "LA___MENT",
            "OA__T",
            "A___ORRED",
            "ZA_____ST",
            "____YAGE",
            "OBLI____NG",
            "VO__E",
            "CLERI____",
            "RA___LINS",
            "LE___D",
            "ZEOL___",
            "__LVE",
            "HOA____",
            "SWEEPS____S",

            "VANDALI___TION",
            "QUE____NG",
            "ATROCI___S",
            "H____NOUS",
            "PR___TE",
            "RELINQ___SH",
            "HABERDA___RY",
            "NA___LLE",
            "MACAQ___",
            "MELAN____LY",
            "INTRI____E",
            "CA___LK",
            "LIN__STIC",
            "TAC__UL",
            "NEG___GENCE",

            "CL__CH",
            "S___SION",
            "L____URELY",
            "FIC__ON",
            "P___DERAST",



    };

    public String mChoices [] [] = {
            {"Confusion","Innocent","Uncertain","Unaware"},
            {"Unforgettable","Threatening","Ugly","Remarkable"},
            {"Flexible","Inspired","Dependable","Inclined"},
            {"Resolute","Uncertain","Forgetful","Clueless"},
            {"Helpless","Useless","Unnecessary","Avoidable"},
            {"Pretentious","Ambitious","Gorgeous","Rebellious"},
            {"Different","Weird","Beautiful","Colorful"},
            {"Forbidden","Surprise","Secret","Unacceptable"},
            {"Brief","Unforgettable","Shinny","Remarkable"},
            {"Dirty","Vulgar","Weird","Bizarre"},
            {"Gravity","Ecstasy","Erotic","Numb"},
            {"Summary","Teaser","Blog","Plot"},
            {"Castle","Forest"," Maze","Box"},
            {"Complicated","Modern","Worldly","Wealthy"},
            {"Belief","Fondness","Hobby","Route"},

            {"Recycled","Refurbished","Updated","Outdated"},
            {"Lively","Awkward","Kindly","Sweetly"},
            {"Naive","Unbelievable","Assertive","Unclear"},
            {"Essential","Crucial","Important","Excessive"},
            {"Disorganized","Blank","Puzzled","Strategic"},
            {"Eager","Careless","Apart","fearful"},
            {"Economy","praise","external","overdoing"},
            {"Pleasing","nervous","aggravating","unclear"},
            {"Gift","theft","lawless","honor"},
            {"Magic","brutal","indictment","belief"},
            {"Temporary","ethical","reformed","endless"},
            {"Exactly","embellish","outer","advance"},
            {"Depend","prove","strict","concourse"},
            {"Enthused","responsive","likely","flexible"},
            {"Edge","stiff","top","under"},
            //30
            {"Ability","Dullness","Time","Tender"},
            {"Fool","Open","Gentleness","Reserved"},
            {"Extension","Welcoming","Celebration","Mourning"},
            {"Gimmick","Selected","Capability","Lustful"},
            {"Boring","Dramatic","Blackball","Mild"},
            {"Genius","Brain","Buffoon","Decent"},
            {"Sensual","Moral","Decent","Trick"},
            {"Reserved","Exclusive","Deception","Merrymaking"},
            {"Plain","Flecked","Simple","Dirty"},
            {"Cleanse","Purify","Dirty","Peace"},
            {"Angelic","Good","Simple","Cruel"},
            {"Actual","Nominal","Contaminate","Commotion"},
            {"Calm","Peace","Doted","Turmoil"},
            {"Difficulty","Advantage","Boon","Maniacal"},
            {"Agitation","Clamor","Dispassion","Traitor"},

            {"Antipathy","Dislike","Penchant","Dilemma"},
            {"Betrayer","Loyalist","Patriot","Inclination"},
            {"Uncommon","Local","Different","Wealth"},
            {"Abundance","Dearth","Native","Deficiency"},
            {"Assist","Support","Preclude","Obvious"},
            {"Obscure","Uncertain","Meddling","Apparent"},
            {"Intrusive","Avoiding","Dodging","Affected"},
            {"Extroverted","Unaffected","Artificial","Wasteful"},
            {"Economical","Extravagant","Mean","Affected"},
            {"Verbose","Wordy","Short","Huge"},
            {"Enormous","Little","Miniature","Brief"},
            {"Safety","Surety","Threat","Clear"},
            {"Understandable","Unclear","Obscure","Peril"},
            {"Lot","Whole","Ounce","Maintain"},
            {"Awareness","Concern","Forgetfulness","Amount"},
            //60
            {"Ruin","Destroy","Repair","Blankness"},
            {"Build","Demolish","Construct","Maintain"},
            {"Dejected","Doleful","Preserve","Elated"},
            {"Discontinue","Preserve","Cease","Attentive"},
            {"Harmless","Healthful","Destructive","Interfering"},
            {"Praise","Laud","Imagine","Defame"},
            {"Timid","Brave","Dark","Loss"},
            {"Impropriety","Disparage","Besmirch","Propriety"},
            {"Harm","Profit","Levity","Bold"},
            {"Inspiring","Comfortless","Damage","Grace"},
            {"Graceful","Cheerless","Absurd","Pleasant"},
            {"Stop","Relapse","Overflow","Levity"},
            {"Cautiously","Hesitantly","Go by","Full"},
            {"Lack","Carefully","Overrun","Pass"},
            {"Skinny","Mumble","Timber","Stocky"},

            {"Loose","Grab","Stout","Thin"},
            {"Overtone","Murmur","Fasten","Catch"},
            {"Unhurt","Hurt","Enunciate","Fellow"},
            {"Uncover","Unharmed","Cover","Need"},
            {"Blame","Hint","Reveal","Praise"},
            {"Warm","Laud","Keen","Promote"},
            {"Information","Glimmer","Mild","Inbred"},
            {"Deep-seated","Acquired","Indication","Embellish"},
            {"Conflict","Friendship","Upset","Rooted"},
            {"Peace","Agitation","Dispute","Accord"},
            {"Faithfulness","Disloyalty","Perturbation","Calmness"},
            {"Stop","Introduce","Allegiance","Bashful"},
            {"Skittish","Aggressive","Calmness","Big"},
            {"Demolish","Contrive","Disturbance","Treachery"},
            {"Formulate","Diligent","Delaying","Playfully"},
            //90
            {"Skillful","Jerk","Superficial","Wise"},
            {"Superficial","Jerk","Damage","Vague"},
            {"Superficial","Blind","Skillful","Damage"},
            {"Jerk","Vague","Superficial","Wise"},
            {"Wise","Superficial","Penetrate","Jerk"},
            {"Damage","Negative reaction","Flattering","Wise"},
            {"Damage","Blind","Wise","Negative reaction"},
            {"Wise","Blind","Flattering","Superficial"},
            {"Blind","Vague","Negative reaction","Superficial"},
            {"Wise","Flattering","Blind","Negative reaction"},
            {"Gimmick","Ploy","Honesty","Festivity"},
            {"Abundant","Exclude","Admit","Limited"},
            {"Aggressive","Timid","Upset","Peace"},
            {"Loyalty","Disloyalty","Destroy","Think up"},
            {"Prank","Play","Study","Eager"},

            {"Dignified","Shameful","Request","Snatch"},
            {"Approve","Censure","Scandalous","Beg"},
            {"Polite","Disdainful","Identical","Happy"},
            {"Sundown","Twilight","Daybreak","Sunset"},
            {"Biased","Unselfish","Neutral","Prejudice"},
            {"Give","Filch","Purloin","Steal"},
            {"Block","Secure","Free","Barricade"},
            {"Appeal","Pray","Request","Order"},
            {"Solemn","Merry","Exultant","Cheerful"},
            {"Amusing","Sad","Funny","Comical"},
            {"Allay","Assuage","Relieve","Increase"},
            {"Lethargy","Patience","Resilience","Fortitude"},
            {"Arrogant","Big talking","Diffident","Egotistical"},
            {"Bogus","False","Genuine","Counterfeit"},
            {"Abandon","Highly","Respect","Admiration"},
            //120
            {"Caricature","Derision","Approval","Contemptuous"},
            {"Banter","Seriousness","Frivolity","Teasing"},
            {"Dislike","Captive","Cherish","Attract"},
            {"Charm","Magic","Spell","Reality"},
            {"Hurry","Boondoggle","Delay","Dawdle"},
            {"Discharge","Accountability","Dispensation","Freedom"},
            {"Capricious","Vacillating","Changeable","Stable"},
            {"Untrue","Imaginary","Authentic","Artificial"},
            {"Angry","Happy","Annoyed","Enraged"},
            {"Complicated","Simple","Easy","Effortless"},
            {"Doubtful","Fickle","Resolute","Indecisive"},
            {"Hunt","Retreat","Search","Seek"},
            {"Cover","Beat","Break","Dig"},
            {"Arrange","Forage","Poke","Ravage"},
            {"Bleak","Chilly","Cold","Warm"},

            {"Interval","Juncture","Break","Pause"},
            {"Heated","Chilly","Freezing","Folly"},
            {"Loose","Rigid","Steely","Flexible"},
            {"Invalid","Allowable","Defensible","Founded"},
            {"Abashment","Abjection","Advantage","Low spirits"},
            {"Conformity","Consent","Agreement","Refusal"},
            {"Ideal","Artificial","Paragon","Perfect"},
            {"Apprehension","Certainty","Anxiety","Doubt"},
            {"Helpful","Offensive","Putrid","Harmful"},
            {"Egotism","Devotion","Humility","Selfishness"},
            {"Enormous","Little","Miniature","Brief"},
            {"Safety","Peril","Threat","Clear"},
            {"Understandable","Unclear","Palpable","Peril"},
            {"Lot","Small","Ounce","Maintain"},
            {"Awareness","Blankness","Forgetfulness","Amount"},
            //150
            {"Renovate","Destroy","Repair","Blankness"},
            {"Build","Demolish","Obliterate","Maintain"},
            {"Ecstatic","Doleful","Preserve","Elated"},
            {"Conserve","Preserve","Cease","Attentive"},
            {"Mortal","Healthful","Destructive","Interfering"},
            {"Praise","Disparage","Imagine","Defame"},
            {"Gallant","Brave","Dark","Fearful"},
            {"Impropriety","Disparage","Besmirch","Propriety"},
            {"Harm","Profit","Benefit","Bold"},
            {"Inspiring","Comfortless","Damage","Grace"},
            {"Odd","Cheerless","Natural","Pleasant"},
            {"Stop","Relapse","Overflow","Levity"},
            {"Cautiously","Hesitantly","Go by","Full"},
            {"Lack","Carefully","Overrun","Pass"},
            {"Skinny","Mumble","Thin","Stocky"},

            {"Loose","Grab","Stout","Thin"},
            {"Mumble","Murmur","Enunciate","Catch"},
            {"Unhurt","Hurt","Enunciate","Fellow"},
            {"Uncover","Unharmed","Cover","Need"},
            {"Laud","Blame","Reveal","Praise"},
            {"Warm","Laud","Keen","Promote"},
            {"Information","Glimmer","Mild","Inbred"},
            {"Deep-seated","Acquired","Indication","Embellish"},
            {"Conflict","Friendship","Upset","Rooted"},
            {"Peace","Agitation","Dispute","Accord"},
            {"Faithfulness","Disloyalty","Perturbation","Calmness"},
            {"Close","Introduce","Allegiance","Bashful"},
            {"Skittish","Aggressive","Calmness","Big"},
            {"Demolish","Contrive","Disturbance","Treachery"},
            {"Formulate","Diligent","Delaying","Playfully"},
            //180
            {"After the exam, I felt too exhausted and famished to eat my foods.","I could eat a horse, I am famish now.","I famished my stomach next time you treat me to a meal out.","I will bring lots of pizza, that’s a famish."},
            {"must","has to","could","would"},
            {"search","to search","searching","for searching"},
            {"to be","I had been","that I may","My"},
            {"foot","feet","foots","feet’s"},
            {"knew","knows","know","known"},
            {"there","their","its","it’s"},
            {"have wrote","has wrote","have written","has written"},
            {"hypothesis","hypotheses","hyphothesises","hypothesess"},
            {"witness","witnesses","witnessed","witnessing"},
            {"Does","Doesn’t","Do","Don’t"},
            {"painting","painted","paint","to paint"},
            {"weak","weaken","weakened","weakening"},
            {"hopeless","hopeful","hopelike","hopely"},
            {"misagree","unagree","inagree","disagree"},

            {"information","informations","infoes","infos"},
            {"sheeps","sheep","ships","ship"},
            {"forget","forgets","forgot","forgotten"},
            {"crush","crushed","crash","crashed"},
            {"hid","hide","hided","hidden"},
            {"will him?","will you?","shall we?","aren't I?"},
            {"aren't you","hasn't she?","did her?","is he?"},
            {"hasn't she?","was she?","did her?","won't they?"},
            {"much","any","some","a"},
            {"he studied","he has studied","studying","study"},
            {"be looking into","be looking at","be looking after","be looking over"},
            {"a","an","the","none"},
            {"a","an","the","none"},
            {"do","has","had","have"},
            {"do","has","had","have"},
            //210   //      {"","","",""},
            {"is","was","are","were"},
            {"Painting","Painted","Paint","To paint"},
            {"With","And","To","Than"},

            {"BE","BI","",""},
            {"HA","A","",""},
            {"QA","CU","",""},
            {"REIN","RINE","",""},
            {"EI","IE","",""},
            {"THY","TYE","",""},
            {"AT","TS","",""},
            {"PE","PI","",""},
            {"MINE","MEN","",""},
            {"E","ED","",""},
            {"ST","SK","",""},
            {"XE","SE","",""},

            {"QUI","CUI","",""},
            {"PALEA","PALE","",""},
            {"KAIL","KALE","",""},
            {"AN","NE","",""},
            {"ID","VE","",""},
            {"KLE","CLE","",""},
            {"BH","H","",""},
            {"NIE","NCE","",""},
            {"QUA","CUA","",""},
            {"GE","GI","",""},
            {"GU","QU","",""},
            {"CAL","KAL","",""},
            {"VE","BE","",""},
            {"VIE","VEI","",""},
            {"ATE","ITE","",""},
            //240
            {"VA","BA","",""},
            {"REIR","RIER","",""},
            {"TEE","TAKE","",""},
            {"ZA","SA","",""},
            {"UIE","UEI","",""},
            {"OU","UO","",""},
            {"EI","IE","",""},
            {"AI","A","",""},
            {"UI","IU","",""},
            {"SHE","CHE","",""},
            {"CE","SE","",""},
            {"UE","UI","",""},
            {"CHO","CHU","",""},
            {"GU","QU","",""},
            {"O","U","",""},

            {"QUI","GUI","",""},
            {"TF","KF","",""},
            {"LI","LE","",""},
            {"UT","AT","",""},
            {"UA","WA","",""},
            {"EIS","IES","",""},
            {"TI","SI","",""},
            {"AE","EA","",""},







    };
    private String mCorrectAnswer[] ={
            "Uncertain", "Threatening", "Inclined", "Resolute", "Useless", "Pretentious", "Weird", "Secret", "Brief", "Vulgar",
            "Ecstasy", "Teaser", "Maze", "Worldly", "Fondness", "Outdated", "Lively", "Assertive", "Excessive", "Disorganized",
            "Eager", "overdoing", "Pleasing", "theft", "belief", "endless", "embellish", "prove", "Enthused", "under",
            "Ability", "Gentleness", "Celebration", "Gimmick", "Dramatic", "Buffoon", "Sensual", "Reserved", "Flecked", "Dirty",
            "Cruel", "Nominal", "Turmoil", "Difficulty", "Dispassion", "Penchant", "Betrayer", "Local", "Abundance","Preclude",
            "Apparent", "Intrusive", "Artificial", "Extravagant", "Short", "Enormous", "Threat", "Understandable", "Ounce", "Forgetfulness",
            "Repair", "Demolish", "Elated", "Preserve", "Destructive", "Defame", "Brave", "Propriety", "Harm", "Comfortless",
            "Absurd", "Relapse", "Cautiously", "Overrun", "Stocky", "Grab", "Murmur", "Hurt", "Cover", "Praise",
            "Warm", "Glimmer", "Deep-seated", "Conflict", "Agitation", "Faithfulness", "Introduce", "Skittish", "Contrive", "Delaying",
            "Jerk", "Superficial", "Skillful", "Wise", "Penetrate", "Damage", "Negative reaction", "Flattering", "Vague", "Blind",
            "Honesty", "Limited", "Aggressive", "Disloyalty", "Study", "Dignified", "Censure", "Polite", "Daybreak", "Biased",
            "Give", "Free", "Order", "Solemn", "Sad", "Increase", "Lethargy", "Diffident", "Genuine", "Abandon",
            "Approval", "Seriousness", "Dislike", "Reality", "Hurry", "Accountability", "Stable", "Authentic", "Happy", "Complicated",
            "Resolute", "Retreat", "Cover", "Arrange", "Warm", "Juncture", "Heated", "Flexible", "Invalid", "Advantage",
            "Refusal", "Artificial", "Certainty", "Helpful", "Humility", "Little", "Safety", "Unclear", "Lot", "Awareness",
            "Destroy","Build" ,"Doleful" ,"Cease", "Healthful", "Praise", "Fearful", "Impropriety", "Benefit", "Inspiring",
            "Natural", "Stop", "Hesitantly", "Lack", "Thin", "Loose", "Enunciate", "Hurt", "Uncover", "Blame",
            "Keen", "Information","Acquired" ,"Friendship", "Peace", "Disloyalty", "Close", "Aggressive", "Demolish", "Diligent",
            "After the exam, I felt too exhausted and famished to eat my foods.", "would", "searching", "My", "feet", "know", "its", "have written", "hypotheses", "witnessed",
            "Don’t", "painted", "weakening", "hopeful", "disagree", "information", "sheep", "forgotten", "crashed", "hidden",
            "shall we?", "is he?", "was she?", "some", "studying", "be looking at", "an", "none", "have", "had",
            "are", "Painted", "Than",

            "BI", "HA", "CU","RINE", "IE","THY", "TS", "PE", "MEN", "ED",
            "SK", "XE", "CUI","PALEA", "KAIL","NE", "VE", "KLE", "BH", "NIE",
            "QUA", "GI", "GU","CAL", "VE","VIE", "ITE", "VA", "RIER", "TAKE",
            "SA", "UIE", "OU","EI", "A","UI", "SHE", "CE", "UE", "CHO",
            "GU", "U", "GUI","TF", "LI","UT", "UA", "EIS", "TI", "AE",


    };
    private String levelQuestions[] ={
      "EASY","AVERAGE","DIFFICULT","EASY","AVERAGE","DIFFICULT","",""
    };
    private String levelQuestionsItems[] = {
            "0-14","15-44","45-89",
            "90-104", "105-134", "135-179",
            "180-212","213-263"
    };
    private String subCateg[] = {
            "SYNONYMS","ANTONYMS","English Grammar and Correct Usage ","SPELLING"
    };

    public String levelQuestion(int val) {
        String level = levelQuestions[val];
        return level;
    }
    public String numberItems(int item){
        String items = levelQuestionsItems[item];
        return items;
    }

    public String getQuestion(int a)
    {
        String questions = mQuestions[a];
        return  questions;
    }
    public String getChoices1(int a)
    {
        String choice = mChoices[a][0];
        return  choice;
    }
    public String getChoices2(int a)
    {
        String choice = mChoices[a][1];
        return  choice;
    }
    public String getChoices3(int a)
    {
        String choice = mChoices[a][2];
        return  choice;
    }
    public String getChoices4(int a)
    {
        String choice = mChoices[a][3];
        return  choice;
    }
    public String getAnswer(int a)
    {
        String answer = mCorrectAnswer[a];
        return answer;
    }
    public String getCateg(int a)
    {
        String categ = subCateg[a];
        return  categ;
    }
}
